---
abstract: 'Read JSON path and output string'
author:
  - 'Michael Vu <email@michael.vu>'
build_requires:
  Try::Tiny: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-ReadPath
requires:
  Getopt::Long: '0'
  JSON::XS: '0'
  Mouse: '0'
  Template: '0'
version: '2'
